### Get all books
GET http://localhost:3000/books

### Get a book by id
GET  http://localhost:3000/books/3

### Get a book by name
GET  http://localhost:3000/books/Test

### Create new book
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "Test",
    "ISBN": "Test ISBN",
    "publishDate": "Test Date",
    "author": "Test Author"
}

### Delete by id
DELETE http://localhost:3000/books/1

### Update by id
PUT http://localhost:3000/books/1
Content-Type: application/json

{
    "title": "Test Title PUT",
    "ISBN": "Test ISBN PUT",
    "publishDate": "Test Date PUT",
    "author": "Test Author PUT"
}